// Code generated by "stringer -type=EnumCltErr,EnumMsgErr -linecomment -output=errors_string.go"; DO NOT EDIT.

package apierr

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeClntUndefined-0]
	_ = x[CodeClntNoHost-1]
	_ = x[CodeClntTargetVerification-2]
	_ = x[CodeClntReqMarshalling-3]
	_ = x[CodeClntHTTPReqCreation-4]
	_ = x[CodeClntHTTPSend-5]
	_ = x[CodeClntHTTPStatus-6]
	_ = x[CodeClntRespJSONUnmarshalling-7]
	_ = x[CodeClntIDMismatch-8]
	_ = x[CodeClntJSONRPCResp-9]
	_ = x[CodeClntCmdCreation-10]
	_ = x[CodeClntRPCReqCreation-11]
	_ = x[CodeClntActNONE-12]
	_ = x[CodeClntActUnsupported-13]
	_ = x[CodeClntNoPort-14]
	_ = x[CodeClntNoUsername-15]
	_ = x[CodeClntNoPassword-16]
	_ = x[CodeClntTLSFilesUnspecified-17]
	_ = x[CodeClntTLSFOpenCA-18]
	_ = x[CodeClntTLSLoadCAPEM-19]
	_ = x[CodeClntTLSLoadCertPair-20]
	_ = x[CodeClntTLSCertParsing-21]
	_ = x[CodeClntCBFuncLowerThanCT-22]
	_ = x[CodeClntCBFuncIsNil-23]
	_ = x[CodeClntCBFuncExec-24]
	_ = x[CodeClntDatastoreUnsupported-25]
}

const _EnumCltErr_name = "undefined errorhost is not set, but mandatorytarget verification errorrequest marshalling errorHTTP request creation errorHTTP send errorHTTP status errorresponse JSON unmarshalling errorrequest and response IDs do not matchJSON-RPC response errorcommand creation errorRPC request creation erroraction can't be NONEunsupported action specifiedport could not be nilusername could not be nilpassword could not be nilone of more files for rootCA / certificate / key are not specifiedfailed to open rootCA filecan't load PEM file for rootCAcan't load PEM file for certificate / key paircertificate parsing errorcallback timeout must be lower than confirm timeoutcallback function is nilcallback function execution errordatastore is not supported for this method"

var _EnumCltErr_index = [...]uint16{0, 15, 45, 70, 95, 122, 137, 154, 187, 224, 247, 269, 295, 315, 343, 364, 389, 414, 480, 506, 536, 582, 607, 658, 682, 715, 757}

func (i EnumCltErr) String() string {
	if i < 0 || i >= EnumCltErr(len(_EnumCltErr_index)-1) {
		return "EnumCltErr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnumCltErr_name[_EnumCltErr_index[i]:_EnumCltErr_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeMsgUndefined-0]
	_ = x[CodeMsgCmdCreation-1]
	_ = x[CodeMsgSetNotAllowedActForTools-2]
	_ = x[CodeMsgSettingMethod-3]
	_ = x[CodeMsgReqAddingCmds-4]
	_ = x[CodeMsgReqMarshalling-5]
	_ = x[CodeMsgReqSettingOutFormat-6]
	_ = x[CodeMsgGettingMethod-7]
	_ = x[CodeMsgYANGSpecNotAllowed-8]
	_ = x[CodeMsgReqSettingYMParams-9]
	_ = x[CodeMsgReqGetDSNotAllowed-10]
	_ = x[CodeMsgReqSetSettingAction-11]
	_ = x[CodeMsgDSCandidateUpdateNoValue-12]
	_ = x[CodeMsgDSToolsSetUpdateOnly-13]
	_ = x[CodeMsgDSToolsCandidateSetOnly-14]
	_ = x[CodeMsgDSCandidateValidateOnly-15]
	_ = x[CodeMsgDSCandidateDiffOnly-16]
	_ = x[CodeMsgDSSpecNotAllowedForUnknownMethod-17]
	_ = x[CodeMsgCLISettingMethod-18]
	_ = x[CodeMsgCLIAddingCmdsInReq-19]
	_ = x[CodeMsgCLISettingOutFormat-20]
	_ = x[CodeMsgCLIMarshalling-21]
	_ = x[CodeMsgRespMarshalling-22]
	_ = x[CodeMsgReqSettingConfirmTimeout-23]
	_ = x[CodeMsgReqSettingDSParams-24]
}

const _EnumMsgErr_name = "undefined errorcommand creation errorno delete or replace actions allowed for method set and datastore TOOLSerror setting method in requesterror adding commands in requestmarshalling errorerror setting output format in requesterror getting methodyang models specification on Request.Params level is not supported for methoderror setting yang models specification on Request.Params leveldatastore is not allowed for method getsetting action error for method setvalue isn't specified or not found in the path for method set and datastore CANDIDATEonly update action is allowed with TOOLS datastore for method setonly CANDIDATE and TOOLS datastores allowed for method setonly CANDIDATE datastore allowed for method validateonly CANDIDATE datastore allowed for method diffdatastore specification on Request.Params level is not supported for unknown methoderror setting cli methoderror adding cli commands in requesterror setting output format for cli methodcli request marshalling errorJSON response marshalling errorconfirm timeout is allowed for SET method onlyerror setting datastore parameters in request (check underlying error)"

var _EnumMsgErr_index = [...]uint16{0, 15, 37, 108, 139, 171, 188, 226, 246, 323, 386, 425, 460, 545, 610, 668, 720, 768, 851, 875, 911, 953, 982, 1013, 1059, 1129}

func (i EnumMsgErr) String() string {
	if i < 0 || i >= EnumMsgErr(len(_EnumMsgErr_index)-1) {
		return "EnumMsgErr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnumMsgErr_name[_EnumMsgErr_index[i]:_EnumMsgErr_index[i+1]]
}
